BACKUP DATABASE User_Actions TO DISK = 'D:\vsc\bd\LAB_5\User_Actions_backup.bak'
GO
USE MASTER
GO


IF OBJECT_ID('SP_RESTORE_USER_ACTIONS', 'P') IS NOT NULL
    DROP PROCEDURE SP_RESTORE_USER_ACTIONS

GO
CREATE PROCEDURE SP_RESTORE_USER_ACTIONS
    @BACKUP_PATH NVARCHAR(500),
    @DATA_DESTINATION NVARCHAR(500)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX)
    IF RIGHT(@DATA_DESTINATION, 1) <> '\'
        SET @DATA_DESTINATION = @DATA_DESTINATION + '\'
    IF DB_ID('USER_ACTIONS') IS NOT NULL
        ALTER DATABASE USER_ACTIONS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    SET @SQL = 'RESTORE DATABASE USER_ACTIONS FROM DISK = ''' + @BACKUP_PATH + ''' WITH REPLACE, ' + 'MOVE ''USER_ACTIONS'' TO ''' + @DATA_DESTINATION + 'USER_ACTIONS.MDF'', ' + 'MOVE ''USER_ACTIONS_LOG'' TO ''' + @DATA_DESTINATION + 'USER_ACTIONS_LOG.LDF'''
    EXEC (@SQL)
    ALTER DATABASE USER_ACTIONS SET MULTI_USER
    PRINT 'SUCCESS'
END
GO

EXEC SP_RESTORE_USER_ACTIONS
    @BACKUP_PATH = 'D:\vsc\bd\LAB_5\User_Actions_backup.bak',
    @DATA_DESTINATION = 'D:\vsc\bd\LAB_5'
