USE User_Actions


DROP TABLE USER_LOGS

--1
CREATE TABLE USER_LOGS (
    ID VARCHAR(100) PRIMARY KEY,
    USERNAME NVARCHAR(50) NOT NULL,
    USER_ACTION NVARCHAR(50) NOT NULL,
    ACTION_DATE DATE NOT NULL,
    ACTION_TIME TIME NOT NULL,
    ACTION_RESULT NVARCHAR(50) NOT NULL,
)

INSERT INTO USER_LOGS (ID, USERNAME, USER_ACTION, ACTION_DATE, ACTION_TIME, ACTION_RESULT)
SELECT TOP (1000000)
    'LOG_' + FORMAT(n, 'D7'),
    'USER_' + FORMAT(n % 500000, 'D6'),
    CASE (n % 5)
        WHEN 0 THEN 'LOGIN'
        WHEN 1 THEN 'LOGOUT'
        WHEN 2 THEN 'PURCHASE'
        WHEN 3 THEN 'VIEW'
        WHEN 4 THEN 'DELETE'
    END,
    DATEADD(DAY, (n % 365), '2025-01-01'),
    CAST(DATEADD(SECOND, (n * 123) % 86400, '00:00:00') AS TIME),
    CASE (n % 4)
        WHEN 0 THEN 'SUCCESS'
        WHEN 1 THEN 'FAILURE'
        WHEN 2 THEN 'PENDING'
        WHEN 3 THEN 'CANCELLED'
    END
FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
    FROM sys.all_columns a
    CROSS JOIN sys.all_columns b
) AS Numbers


SELECT * FROM USER_LOGS


--2
IF EXISTS (SELECT * FROM sys.partition_schemes WHERE name = 'ps_LOGS_IN_MONTHS')
    DROP PARTITION SCHEME ps_LOGS_IN_MONTHS

IF EXISTS (SELECT * FROM sys.partition_functions WHERE name = 'pf_LOGS_IN_MONTHS')
    DROP PARTITION FUNCTION pf_LOGS_IN_MONTHS

GO
CREATE PARTITION FUNCTION pf_LOGS_IN_MONTHS(DATE)
AS RANGE RIGHT FOR VALUES (
    '2025-02-01', '2025-03-01', '2025-04-01', '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01'
)
GO

GO
CREATE PARTITION SCHEME ps_LOGS_IN_MONTHS
AS PARTITION pf_LOGS_IN_MONTHS ALL TO ([PRIMARY])
GO

CREATE TABLE USER_LOGS_PARTITIONED (
    ID VARCHAR(100),
    USERNAME NVARCHAR(50) NOT NULL,
    USER_ACTION NVARCHAR(50) NOT NULL,
    ACTION_DATE DATE NOT NULL,
    ACTION_TIME TIME NOT NULL,
    ACTION_RESULT NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_USER_LOGS_PARTITIONED PRIMARY KEY (ID, ACTION_DATE)
) ON ps_LOGS_IN_MONTHS(ACTION_DATE)

INSERT INTO USER_LOGS_PARTITIONED (ID, USERNAME, ACTION_DATE, ACTION_TIME, ACTION_RESULT, USER_ACTION)
SELECT ID, USERNAME, ACTION_DATE, ACTION_TIME, ACTION_RESULT, USER_ACTION FROM USER_LOGS


DROP TABLE USER_LOGS


GO
EXEC sp_rename 'USER_LOGS_PARTITIONED', 'USER_LOGS'
GO
GO
EXEC sp_rename 'PK_USER_LOGS_PARTITIONED', 'PK_USER_LOGS'
GO

SELECT COUNT(*) AS PartitionCount FROM sys.partitions
WHERE object_id = OBJECT_ID('USER_LOGS')

SELECT p.partition_number AS PartitionNumber, p.rows AS RowsCount FROM sys.partitions p
WHERE p.object_id = OBJECT_ID('USER_LOGS') ORDER BY p.partition_number
