USE LAB_2

CREATE TABLE STUD
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LAST_NAME NVARCHAR(30),
    F_NAME NVARCHAR(30),
    S_NAME NVARCHAR(30),
    BR_DATE DATE,
    IN_DATE DATE,
    EXM FLOAT
);

CREATE TABLE FACULTY 
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FACULTY_NAME NVARCHAR(50)
);

CREATE TABLE FORM
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FORM_NAME NVARCHAR(30)
);

CREATE TABLE HOURS 
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE INT,
    FACULTY_ID INT,
    FORM_ID INT,
    ALL_H INT,
    INCLASS_H INT,
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(ID)
);

CREATE TABLE PROCESS
(
    STUD_ID INT,
    HOURS_ID INT,
    PRIMARY KEY (STUD_ID, HOURS_ID),
    FOREIGN KEY (STUD_ID) REFERENCES STUD(ID),
    FOREIGN KEY (HOURS_ID) REFERENCES HOURS(ID)
);

CREATE TABLE SUBJ
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUBJ NVARCHAR(30),
    HOURS INT
);

CREATE TABLE TEACH
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LAST_NAME NVARCHAR(30),
    F_NAME NVARCHAR(30),
    S_NAME NVARCHAR(30),
    BR_DATE DATE,
    START_WORK_DAY DATE
);

CREATE TABLE WORK
(
    TEACH_ID INT,
    SUBJ_ID INT,
    HOURS_ID INT,
    PRIMARY KEY(TEACH_ID, SUBJ_ID, HOURS_ID),
    FOREIGN KEY(HOURS_ID) REFERENCES HOURS(ID),
    FOREIGN KEY(SUBJ_ID) REFERENCES SUBJ(ID),
    FOREIGN KEY(TEACH_ID) REFERENCES TEACH(ID)
);


INSERT INTO STUD (LAST_NAME, F_NAME, S_NAME, BR_DATE, IN_DATE, EXM) VALUES 
('Иванов', 'Иван', 'Иванович', '2005-05-15', '2015-09-01', 4.0),
('Петрова', 'Анна', 'Сергеевна', '2004-11-20', '2014-09-01', 5.0),
('Ботяновский', 'Алексей', 'Петрович', '2005-02-10', '2014-09-01', 10.0),
('Кузнецова', 'Мария', 'Дмитриевна', '2006-07-05', '2014-09-01', 7.0),
('Смирнов', 'Игорь', 'Николаевич', '2005-03-12', '2023-09-01', 9.0),
('Волкова', 'Елена', 'Викторовна', '2004-09-30', '2014-09-01', 3.0),
('Попов', 'Дмитрий', 'Олегович', '2005-12-25', '2015-09-01', 8.0),
('Зингель', 'Артем', 'Игоревич', '2006-01-15', '2014-09-01', 6.0),
('Зайцева', 'Ольга', 'Александровна', '2005-06-20', '2015-09-01', 2.0),
('Васильев', 'Павел', 'Андреевич', '2004-02-14', '2015-09-01', 10.0),
('Трудолюбов', 'Антон', 'Игоревич', '1975-04-10', '2015-09-01', 9.0),
('Сникерс', 'Джек', NULL, '1998-04-12', '2023-09-01', 4.5),
('Джесика', 'НеПойдётСтобойНаБал', NULL, '2000-02-22', '2023-09-01', 10.0),
('Мюллер', 'Арбуз', NULL, '2001-09-11', '2023-09-01', 8.5),
('Умнов', 'Гений', 'Маркович', '2005-01-01', '2023-09-01', 10.0),
('Блестящая', 'Любовь', 'Викторовна', '2006-03-15', '2023-09-01', 10.0),
('Мудрый', 'Ярослав', 'Олегович', '2004-12-10', '2022-09-01', 10.0),
('Пятёркина', 'Вера', 'Павловна', '2005-05-05', '2023-09-01', 10.0),
('Знающий', 'Олег', 'Игоревич', '2004-08-20', '2022-09-01', 10.0),
('Эйнштейн', 'Альберт', NULL, '2003-02-14', '2023-09-01', 10.0),
('Ломоносов', 'Михаил', 'Васильевич', '2005-11-19', '2023-09-01', 10.0),
('Тесла', 'Никола', NULL, '2004-07-10', '2022-09-01', 10.0),
('Ленивцев', 'Илья', 'Андреевич', '2005-10-10', '2023-09-01', 2.5),
('Прогульщиков', 'Денис', 'Сергеевич', '2006-01-20', '2023-09-01', 2.0),
('Спящий', 'Антон', 'Николаевич', '2004-04-04', '2022-09-01', 3.2),
('Забывчивая', 'Яна', 'Юрьевна', '2005-09-09', '2023-09-01', 3.5),
('Тормозов', 'Виктор', 'Петрович', '2003-12-12', '2022-09-01', 2.8),
('Хвостов', 'Аркадий', 'Львович', '2005-02-28', '2023-09-01', 3.0),
('Давыдов', 'Алексей', 'Александрович', '1999-09-09', '2024-09-01', 2.0),
('Отличников', 'Виктор', 'Сергеевич', '2005-01-10', '2023-09-01', 9.5),
('Умнова', 'Дарья', 'Алексеевна', '2006-03-22', '2023-09-01', 8.2),
('Золотарев', 'Максим', 'Игоревич', '2005-11-12', '2023-09-01', 7.0);

INSERT INTO FACULTY (FACULTY_NAME) VALUES 
('ИКАД'),
('ИКР'),
('ФПМ'),
('ФПК'),
('ФИТ');

INSERT INTO FORM (FORM_NAME) VALUES 
('Очная'),
('Заочная'),
('Очно-заочная'),
('Дистанционная');

INSERT INTO HOURS (COURSE, FACULTY_ID, FORM_ID, ALL_H, INCLASS_H) VALUES 
(1, 1, 1, 250, 120),
(2, 1, 2, 180, 20),
(3, 2, 1, 210, 180),
(1, 2, 2, 160, 110),
(1, 3, 1, 300, 140),
(2, 3, 2, 150, 30),
(3, 4, 4, 120, 10),
(3, 1, 2, 200, 45),
(3, 4, 2, 200, 30),
(1, 1, 1, 400, 180),
(1, 5, 1, 320, 160);

INSERT INTO PROCESS (STUD_ID, HOURS_ID) VALUES 
(1, 9),
(2, 1),
(3, 4),
(4, 4),
(5, 2),
(6, 5),
(7, 6),
(8, 7),
(9, 8),
(10, 4),
(11, 9),
(12, 1),
(13, 5),
(14, 3),
(15, 1),
(16, 3),
(17, 5),
(18, 7),
(19, 9),
(20, 10),
(21, 1),
(22, 3),
(23, 2),
(24, 4),
(25, 6),
(26, 8),
(27, 10),
(28, 2),
(29, 1),
(30, 11),
(31, 11),
(32, 11);

INSERT INTO SUBJ (SUBJ, HOURS) VALUES 
('Высшая математика', 102),
('Физика', 72),
('Программирование C++', 120),
('Базы данных', 94),
('История', 112),
('Иностранный язык', 110),
('Архитектура ЭВМ', 250),
('Операционные системы', 220),
('Сети и телекоммуникации', 180);

INSERT INTO TEACH (LAST_NAME, F_NAME, S_NAME, BR_DATE, START_WORK_DAY) VALUES 
('Петровенко', 'Петр', NULL, '1975-03-10', '2010-09-01'),
('Сидоров', 'Сидор', 'Сидорович', '1982-11-22', '2015-02-10'),
('Андреева', 'Анна', 'Сергеевна', '1990-05-05', '2018-09-01'),
('Николаев', 'Николай', 'Николаевич', '1968-12-12', '2000-01-15'),
('Филимон', 'Джон', 'Альбертович', '1970-01-05', '2014-09-01'),
('Иванов', 'Иван', 'Иванович', '1980-01-01', '2010-09-01'),
('Кузнецов', 'Олег', 'Петрович', '1978-05-12', '2012-02-15'),
('Смирнова', 'Елена', 'Игоревна', '1985-10-20', '2016-09-01');

INSERT INTO WORK (TEACH_ID, SUBJ_ID, HOURS_ID) VALUES 
(1, 1, 1), 
(1, 7, 1), 
(1, 9, 1),
(2, 3, 1), 
(2, 4, 3), 
(5, 1, 6), 
(2, 2, 1),
(4, 2, 1), 
(4, 2, 7), 
(4, 7, 3),
(6, 8, 1), 
(6, 3, 2),
(7, 9, 1), 
(7, 9, 2),
(3, 5, 5),
(5, 1, 2),
(8, 6, 1);


SELECT * FROM STUD;
SELECT * FROM FACULTY;
SELECT * FROM FORM;
SELECT * FROM HOURS;
SELECT * FROM PROCESS;
SELECT * FROM WORK;
SELECT * FROM SUBJ;
SELECT * FROM TEACH;


--SELECT
--1
SELECT FACULTY.FACULTY_NAME, AVG(STUD.EXM) AS AVERAGE_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE FORM.FORM_NAME = 'Заочная'
GROUP BY FACULTY.FACULTY_NAME;

--2
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, MAX(STUD.EXM) AS MAXIMAL_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE;

--3
SELECT FACULTY.FACULTY_NAME, AVG(STUD.EXM) AS AVERAGE_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME HAVING AVG(STUD.EXM) > 7.0;

--4
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME, AVG(STUD.EXM) AS AVERAGE_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME HAVING AVG(STUD.EXM) > 7.5;

--5
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, MIN(STUD.EXM) AS MINIMAL_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE;

--6
SELECT FACULTY.FACULTY_NAME, MIN(STUD.EXM) AS MINIMAL_EXAM_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME HAVING MIN(STUD.EXM) > 6.0;

--7
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, (HOURS.ALL_H - HOURS.INCLASS_H) AS SELF_STUDY_HOURS FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE FACULTY.FACULTY_NAME = 'ФПК' AND FORM.FORM_NAME = 'Заочная' AND HOURS.COURSE = 3
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE, (HOURS.ALL_H - HOURS.INCLASS_H);

--8
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME, HOURS.INCLASS_H, (HOURS.ALL_H - HOURS.INCLASS_H) AS SELF_STUDY FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME, HOURS.ALL_H, HOURS.INCLASS_H HAVING (HOURS.ALL_H - HOURS.INCLASS_H) > 150;

--9
SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, COUNT(WORK.SUBJ_ID) AS COUNT_OF_SUBJECTS FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
GROUP BY TEACH.ID, TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME;

--10
SELECT FACULTY.FACULTY_NAME, COUNT(WORK.TEACH_ID) AS COUNT_OF_PREPODS FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
GROUP BY FACULTY.FACULTY_NAME;

--11
SELECT SUBJ.SUBJ, MAX(HOURS.ALL_H) AS MAXIMAL_HOURS FROM SUBJ
JOIN WORK ON SUBJ.ID = WORK.SUBJ_ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID 
GROUP BY SUBJ.SUBJ;

--12
SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, COUNT(WORK.SUBJ_ID) AS COUNT_OF_SUBJECTS FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
GROUP BY TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME HAVING COUNT(WORK.SUBJ_ID) > 1;

--13
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, SUM(HOURS.ALL_H) AS COUNT_OF_HOURS_AT_ALL FROM HOURS
JOIN PROCESS ON HOURS.ID = PROCESS.HOURS_ID
JOIN STUD ON PROCESS.STUD_ID = STUD.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE;

--14
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, COUNT(WORK.SUBJ_ID) AS COUNT_OF_SUBJECTS FROM FACULTY
JOIN HOURS ON FACULTY.ID = HOURS.FACULTY_ID
JOIN WORK ON HOURS.ID = WORK.HOURS_ID
WHERE HOURS.COURSE = 2
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE ORDER BY FACULTY.FACULTY_NAME DESC, HOURS.COURSE ASC;

--15
SELECT FACULTY.FACULTY_NAME, COUNT(DISTINCT WORK.SUBJ_ID) AS FOREIGN_SUBJ_COUNT FROM WORK
JOIN TEACH ON WORK.TEACH_ID = TEACH.ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE TEACH.S_NAME IS NULL
GROUP BY FACULTY.FACULTY_NAME;


--JOIN
--1
SELECT STUD.LAST_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE FORM.FORM_NAME = 'Заочная' AND DATEADD(YEAR, 37, STUD.BR_DATE) > GETDATE();

--2
SELECT FACULTY.FACULTY_NAME, COUNT(PROCESS.STUD_ID) AS STUDENT_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
GROUP BY FACULTY.FACULTY_NAME;

--3
SELECT FORM.FORM_NAME, COUNT(PROCESS.STUD_ID) AS STUDENT_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FORM.FORM_NAME;

--4
SELECT FACULTY.FACULTY_NAME, AVG(DATEDIFF(YEAR, STUD.BR_DATE, GETDATE())) AS AVG_AGE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
GROUP BY FACULTY.FACULTY_NAME;

--5
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.IN_DATE, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE STUD.S_NAME IS NULL
GROUP BY STUD.LAST_NAME, STUD.F_NAME, FACULTY.FACULTY_NAME, FORM.FORM_NAME, HOURS.COURSE, STUD.IN_DATE;

--6
SELECT TOP 1 FACULTY.FACULTY_NAME, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE YEAR(STUD.IN_DATE) = 2015
GROUP BY FACULTY.FACULTY_NAME ORDER BY STUDENTS_COUNT DESC;

--7
SELECT FACULTY.FACULTY_NAME, FORM.FORM_NAME, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE YEAR(STUD.IN_DATE) = 2014
GROUP BY FACULTY.FACULTY_NAME, FORM.FORM_NAME ORDER BY STUDENTS_COUNT;

--8
SELECT DISTINCT FACULTY.FACULTY_NAME FROM FORM
JOIN HOURS ON FORM.ID = HOURS.FORM_ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE FORM.FORM_NAME = 'Заочная';

--9
SELECT DISTINCT FACULTY.FACULTY_NAME, FORM.FORM_NAME, HOURS.COURSE FROM FORM
JOIN HOURS ON FORM_ID = HOURS.FORM_ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID

--10
SELECT FACULTY.FACULTY_NAME, FORM.FORM_NAME, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
GROUP BY FACULTY.FACULTY_NAME, FORM.FORM_NAME;

--11
SELECT HOURS.COURSE, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
WHERE HOURS.COURSE = 1 OR HOURS.COURSE = 3
GROUP BY HOURS.COURSE;

--12
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, COUNT(PROCESS.STUD_ID) AS FOREIGN_STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE STUD.S_NAME IS NULL  
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE;

--13
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE HAVING AVG(STUD.EXM) > 7.5;

--14
SELECT FACULTY.FACULTY_NAME, FORM.FORM_NAME, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID 
WHERE DATEADD(YEAR, 45, STUD.BR_DATE) < GETDATE()
GROUP BY FACULTY.FACULTY_NAME, FORM.FORM_NAME;

--15
SELECT FACULTY.FACULTY_NAME, FORM.FORM_NAME, HOURS.COURSE, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID 
WHERE DATEADD(YEAR, 27, STUD.BR_DATE) > GETDATE()
GROUP BY FACULTY.FACULTY_NAME, FORM.FORM_NAME, HOURS.COURSE;

--16
SELECT FACULTY.FACULTY_NAME, COUNT(PROCESS.STUD_ID) AS STUDENTS_COUNT FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE STUD.LAST_NAME LIKE 'С%'  
GROUP BY FACULTY.FACULTY_NAME;

--PODZAPROSI
--1
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME, STUD.EXM FROM STUD
WHERE STUD.EXM < ((SELECT MAX(STUD.EXM) FROM STUD) * 0.8);
--WHERE STUD.EXM = ((SELECT MAX(STUD.EXM) FROM STUD) * 0.8);

--2
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME, STUD.EXM FROM STUD
WHERE STUD.EXM = (SELECT MAX(STUD.EXM) FROM STUD);

--3
SELECT STUD.LAST_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
WHERE HOURS.FACULTY_ID IN 
(
    SELECT HOURS.FACULTY_ID FROM HOURS
    JOIN PROCESS ON HOURS.ID = PROCESS.HOURS_ID
    GROUP BY HOURS.FACULTY_ID HAVING COUNT(PROCESS.STUD_ID) >= ALL 
    (
        SELECT COUNT(PROCESS.STUD_ID) FROM HOURS
        JOIN PROCESS ON HOURS.ID = PROCESS.HOURS_ID
        GROUP BY HOURS.FACULTY_ID
    )
);

--4
SELECT STUD.LAST_NAME, STUD.F_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE HOURS.ID NOT IN 
(
    SELECT DISTINCT PROCESS.HOURS_ID FROM STUD
    JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
    WHERE STUD.S_NAME IS NULL
);

--5
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
WHERE HOURS.COURSE IN 
(
    SELECT HOURS.COURSE FROM STUD
    JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
    JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
    WHERE STUD.LAST_NAME = 'Ботяновский'
) AND STUD.LAST_NAME != 'Ботяновский';

--6
SELECT DISTINCT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
WHERE HOURS.COURSE IN 
(
    SELECT HOURS.COURSE FROM STUD
    JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
    JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
    WHERE STUD.LAST_NAME = 'Зингель' OR STUD.LAST_NAME = 'Зайцева'
) AND STUD.LAST_NAME != 'Зингель' AND STUD.LAST_NAME != 'Зайцева';

--7
SELECT STUD.LAST_NAME, STUD.F_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE PROCESS.HOURS_ID IN 
(
    SELECT PROCESS.HOURS_ID FROM STUD
    JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
    WHERE STUD.S_NAME IS NULL 
    GROUP BY PROCESS.HOURS_ID HAVING COUNT(STUD.ID) > 1
);

--8
SELECT STUD.LAST_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, (SELECT COUNT(PROCESS.STUD_ID) FROM PROCESS WHERE PROCESS.HOURS_ID = HOURS.ID) AS ALL_STUDENTS FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
WHERE STUD.S_NAME IS NULL;


--PROCEDURES
--1
GO
    CREATE OR ALTER PROCEDURE COUNT_STUDENTS
    @FACULTY_NAME NVARCHAR(50),
    @FORM_NAME NVARCHAR(30)
    AS
    BEGIN
        DECLARE @COUNT INT;
        SELECT @COUNT = COUNT(PROCESS.STUD_ID) FROM PROCESS
        JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
        JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
        JOIN FORM ON HOURS.FORM_ID = FORM.ID
        WHERE FACULTY.FACULTY_NAME = @FACULTY_NAME AND FORM.FORM_NAME = @FORM_NAME;
        PRINT 'Факультет: ' + @FACULTY_NAME;
        PRINT 'Форма обучения: ' + @FORM_NAME;
        PRINT 'Количество студентов: ' + CAST(@COUNT AS NVARCHAR(10));
    END;
GO

EXEC dbo.COUNT_STUDENTS 'ИКАД', 'Очная';

--2
GO
CREATE OR ALTER PROCEDURE COUNT_SUBJECTS
        @COUNT_FPK INT OUTPUT, 
        @COUNT_FPM INT OUTPUT, 
        @SAME_SUBJECTS INT OUTPUT
AS
BEGIN
    SELECT @COUNT_FPK = COUNT(DISTINCT WORK.SUBJ_ID) FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПК';
    SELECT @COUNT_FPM = COUNT(DISTINCT WORK.SUBJ_ID) FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПМ';
    SELECT @SAME_SUBJECTS = COUNT(DISTINCT WORK.SUBJ_ID) FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПК' AND WORK.SUBJ_ID IN 
    (
        SELECT WORK.SUBJ_ID FROM WORK
        JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
        JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
        WHERE FACULTY.FACULTY_NAME = 'ФПМ'
    );
    DECLARE @UNIQUE_SUBJECTS INT = @COUNT_FPK + @COUNT_FPM;
    PRINT CONCAT('Для ФПК читается ', @COUNT_FPK, ' предметов,');
    PRINT CONCAT('Для ФПМ читается ', @COUNT_FPM, ' предметов,');
    PRINT CONCAT('Всего предметов ', @UNIQUE_SUBJECTS, ' (из которых ', @SAME_SUBJECTS, ' идентичны).');
END;
GO

DECLARE @FPK INT, @FPM INT, @SAME INT;
EXEC COUNT_SUBJECTS @FPK OUTPUT, @FPM OUTPUT, @SAME OUTPUT;

--3
GO
CREATE OR ALTER PROCEDURE ADD_STUDENT_TO_FIRST_COURSE
    @FACULTY_NAME NVARCHAR(50),
    @FORM_NAME NVARCHAR(30),
    @BIRTH_DATE DATE,
    @ADMISSION_DATE DATE,
    @LAST_NAME NVARCHAR(30),
    @F_NAME NVARCHAR(30),
    @S_NAME NVARCHAR(30)
AS
BEGIN
    DECLARE @FACULTY_ID INT;
    DECLARE @FORM_ID INT;
    DECLARE @HOURS_ID INT;
    DECLARE @NEW_STUD_ID INT;
    SELECT @FACULTY_ID = FACULTY.ID FROM FACULTY 
    WHERE FACULTY.FACULTY_NAME = @FACULTY_NAME;
    SELECT @FORM_ID = FORM.ID FROM FORM 
    WHERE FORM.FORM_NAME = @FORM_NAME;
    SELECT @HOURS_ID = HOURS.ID FROM HOURS 
    WHERE HOURS.FACULTY_ID = @FACULTY_ID AND HOURS.FORM_ID = @FORM_ID AND HOURS.COURSE = 1;
    IF @FACULTY_ID IS NULL
    BEGIN
        PRINT 'Ошибка. Факультет "' + @FACULTY_NAME + '" не найден.';
        RETURN;
    END
    IF @FORM_ID IS NULL
    BEGIN
        PRINT 'Ошибка. Форма обучения "' + @FORM_NAME + '" не найдена.';
        RETURN;
    END
    IF @HOURS_ID IS NULL
    BEGIN
        PRINT 'Ошибка. Комбинация факультета и формы обучения для 1 курса не существует.';
        RETURN;
    END
    INSERT INTO STUD (LAST_NAME, F_NAME, S_NAME, BR_DATE, IN_DATE) VALUES 
    (@LAST_NAME, @F_NAME, @S_NAME, @BIRTH_DATE, @ADMISSION_DATE);
    SELECT @NEW_STUD_ID = MAX(STUD.ID) FROM STUD;
    INSERT INTO PROCESS (STUD_ID, HOURS_ID) VALUES (@NEW_STUD_ID, @HOURS_ID);
    PRINT 'Студент ' + @LAST_NAME + ' успешно зачислен на 1 курс.';
END;
GO

EXEC ADD_STUDENT_TO_FIRST_COURSE 
    @FACULTY_NAME = 'ФПК', 
    @FORM_NAME = 'Заочная', 
    @BIRTH_DATE = '2005-05-15', 
    @ADMISSION_DATE = '2023-09-01', 
    @LAST_NAME = 'Иванов', 
    @F_NAME = 'Иван', 
    @S_NAME = 'Иванович';


--FUNCTIONS
--1
GO
    CREATE OR ALTER FUNCTION IS_FOREIGN
    (
        @S_NAME NVARCHAR(30)
    )
    RETURNS NVARCHAR(30) AS
    BEGIN
        IF (@S_NAME IS NULL)
            BEGIN
                RETURN 'Иностранец'
            END
        RETURN 'Гражданин'
    END;
GO

SELECT STUD.LAST_NAME, STUD.S_NAME, dbo.IS_FOREIGN(STUD.S_NAME) AS STATUS FROM STUD;

--2
GO
    CREATE OR ALTER FUNCTION WORKLOAD()
    RETURNS TABLE AS
    RETURN
    (
        SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, SUM(SUBJ.HOURS) AS WORKLOAD FROM WORK
        JOIN TEACH ON WORK.TEACH_ID = TEACH.ID
        JOIN SUBJ ON WORK.SUBJ_ID = SUBJ.ID
        GROUP BY TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME
    );
GO

SELECT * FROM dbo.WORKLOAD();


--VIEW
--1
GO
CREATE OR ALTER VIEW STUDENTS_INFO AS 
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE FACULTY.FACULTY_NAME = 'ФПК'
GO

SELECT * FROM STUDENTS_INFO;

GO
CREATE OR ALTER VIEW EXTERNAL_STUDENTS AS 
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, HOURS.ALL_H FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE FORM.FORM_NAME = 'Заочная'
GO

SELECT * FROM EXTERNAL_STUDENTS;

GO
CREATE OR ALTER VIEW ACHIEVEMENT_STUDENTS AS 
SELECT FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME, COUNT(STUD.ID) AS COUNT_OF_ACHIVMENT_STUDENTS FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE STUD.EXM > 8.0
GROUP BY FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME
GO

SELECT * FROM ACHIEVEMENT_STUDENTS;

GO
CREATE OR ALTER VIEW FAILURE_STUDENTS AS 
SELECT STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME, AVG(STUD.EXM) AS AVERAGE_SCORE FROM STUD
JOIN PROCESS ON STUD.ID = PROCESS.STUD_ID
JOIN HOURS ON PROCESS.HOURS_ID = HOURS.ID
JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
JOIN FORM ON HOURS.FORM_ID = FORM.ID
WHERE STUD.EXM < 6.0
GROUP BY STUD.LAST_NAME, STUD.F_NAME, STUD.S_NAME, FACULTY.FACULTY_NAME, HOURS.COURSE, FORM.FORM_NAME
GO

SELECT * FROM FAILURE_STUDENTS;

--2
--STUDENTS_INFO и EXTERNAL_STUDENTS это модифицирующие, потому что они просто показывают данные из таблиц через JOIN
--ACHIEVEMENT_STUDENTS и FAILURE_STUDENTS это только чтение, потому что в них есть группировка GROUP BY
--и расчеты типа COUNT или AVG, из-за которых сервер не сможет сообразить, какую именно запись в исходной таблице нужно обновить


--UNION
--1
SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, SUM(HOURS.ALL_H) AS TOTAL_HOURS, '20%' AS SUPPLEMENT FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
GROUP BY TEACH.ID, TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME HAVING SUM(HOURS.ALL_H) > 450
UNION ALL
SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, SUM(HOURS.ALL_H) AS TOTAL_HOURS, '10%' AS SUPPLEMENT FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
GROUP BY TEACH.ID, TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME HAVING SUM(HOURS.ALL_H) > 300 AND SUM(HOURS.ALL_H) <= 450
UNION ALL
SELECT TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME, SUM(HOURS.ALL_H) AS TOTAL_HOURS, '0%' AS SUPPLEMENT FROM TEACH
JOIN WORK ON TEACH.ID = WORK.TEACH_ID
JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
GROUP BY TEACH.ID, TEACH.LAST_NAME, TEACH.F_NAME, TEACH.S_NAME HAVING SUM(HOURS.ALL_H) <= 300;

--2
SELECT STUD.LAST_NAME, 'РБ' AS STATUS FROM STUD WHERE STUD.S_NAME IS NOT NULL
UNION ALL
SELECT STUD.LAST_NAME, 'Иностранец' AS STATUS FROM STUD WHERE STUD.S_NAME IS NULL
UNION ALL
SELECT TEACH.LAST_NAME, 'РБ' AS STATUS FROM TEACH WHERE TEACH.S_NAME IS NOT NULL
UNION ALL
SELECT TEACH.LAST_NAME, 'Иностранец' AS STATUS FROM TEACH WHERE TEACH.S_NAME IS NULL;

--3
SELECT * FROM TEACH 
WHERE TEACH.ID IN 
(
    SELECT TEACH_ID FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПК'
    INTERSECT
    SELECT TEACH_ID FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПМ'
);

--4
SELECT * FROM TEACH 
WHERE TEACH.ID IN 
(
    SELECT TEACH_ID FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПК'
    EXCEPT
    SELECT TEACH_ID FROM WORK
    JOIN HOURS ON WORK.HOURS_ID = HOURS.ID
    JOIN FACULTY ON HOURS.FACULTY_ID = FACULTY.ID
    WHERE FACULTY.FACULTY_NAME = 'ФПМ'
);

--5
SELECT 'Студентов' AS Тип, COUNT(*) AS [Количество] FROM STUD
UNION ALL
SELECT 'Преподавателей', COUNT(*) FROM TEACH
UNION ALL
SELECT 'Всего человек', (SELECT COUNT(*) FROM STUD) + (SELECT COUNT(*) FROM TEACH);


DROP TABLE PROCESS;
DROP TABLE WORK;
DROP TABLE HOURS;
DROP TABLE STUD;
DROP TABLE TEACH;
DROP TABLE SUBJ;
DROP TABLE FACULTY;
DROP TABLE FORM;

DROP PROCEDURE COUNT_STUDENTS;
DROP PROCEDURE COUNT_SUBJECTS;
DROP PROCEDURE ADD_STUDENT_TO_FIRST_COURSE;

DROP FUNCTION IS_FOREIGN;
DROP FUNCTION WORKLOAD;

DROP VIEW STUDENTS_INFO;
DROP VIEW EXTERNAL_STUDENTS;
DROP VIEW ACHIEVEMENT_STUDENTS;
DROP VIEW FAILURE_STUDENTS;
