USE LAB_1

CREATE TABLE GROUPS
(
    ID_GROUP INT IDENTITY (1,1) PRIMARY KEY,
    GROUP_NAME NVARCHAR(30),
    COURSE INT,
)

CREATE TABLE STUDENTS
(
    ID_STUDENT INT IDENTITY (1,1) PRIMARY KEY,
    NAME NVARCHAR(50),
    SURNAME NVARCHAR(50),
    FATHER_NAME NVARCHAR(50),
    BIRTHDAY NVARCHAR(10),
    ID_GROUP INT,
    FOREIGN KEY (ID_GROUP) REFERENCES GROUPS(ID_GROUP),
)

CREATE TABLE SUBJECTS
(
    ID_SUBJECT INT IDENTITY (1,1) PRIMARY KEY,
    SUBJECT_NAME NVARCHAR(50),
    HOURS_PER_SUBJECT INT,
)

CREATE TABLE PLANS
(
    ID_GROUP INT,
    ID_SUBJECT INT,
    PRIMARY KEY (ID_GROUP, ID_SUBJECT),
    FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID_SUBJECT),
    FOREIGN KEY (ID_GROUP) REFERENCES GROUPS(ID_GROUP),
)

INSERT INTO GROUPS (GROUP_NAME, COURSE) VALUES
    ('PO135', 1),
    ('PO135', 1),
    ('PO235', 2),
    ('PO235', 2),
    ('PO335', 3),
    ('PO335', 3);

INSERT INTO SUBJECTS (SUBJECT_NAME, HOURS_PER_SUBJECT) VALUES
    ('PHYSICS', 200),
    ('MATH', 120),
    ('BASE ALGORITHMIZATION', 70),
    ('DATABASE DESIGN', 130),
    ('VISUAL PROGRAMMING TOOLS', 90),
    ('OOP', 70);

INSERT INTO STUDENTS (NAME,SURNAME, FATHER_NAME, BIRTHDAY, ID_GROUP) VALUES
    ('Fedorenko ', 'P.','R.', '25.12.1997', 1),
    ('Zingel ', 'O.',' ', '25.12.1985', 2),
    ('Savitskayan ', 'N.',' ', '22.09.1987', 3),
    ('Kovalchuk ', 'M.','E.', '17.06.1992', 4),    
    ('Kovrigo ', 'T.','R.', '13.05.1992', 5),    
    ('Shpanko ', 'N.',' ', '14.08.1992', 6);

UPDATE GROUPS SET GROUP_NAME = 'PO134' WHERE GROUP_NAME = 'PO135'

DELETE FROM GROUPS WHERE GROUP_NAME = 'PO135'

UPDATE SUBJECTS SET HOURS_PER_SUBJECT += 30 WHERE SUBJECT_NAME IN ('VISUAL PROGRAMMING TOOLS', 'OOP')

ALTER TABLE SUBJECTS ADD ATESTATION_FORM NVARCHAR (30)
UPDATE SUBJECTS SET ATESTATION_FORM = 'ZACHET' WHERE SUBJECT_NAME = 'BASE ALGORITHMIZATION'
UPDATE SUBJECTS SET ATESTATION_FORM = 'EXAM' WHERE SUBJECT_NAME IN ('PHYSICS', 'MATH', 'DATABASE DESIGN', 'VISUAL PROGRAMMING TOOLS', 'OOP')

ALTER TABLE STUDENTS DROP COLUMN FATHER_NAME


SELECT * FROM STUDENTS
SELECT * FROM GROUPS
SELECT * FROM SUBJECTS


DROP TABLE STUDENTS
DROP TABLE GROUPS
DROP TABLE PLANS
DROP TABLE SUBJECTS
